[mouse]
bindings = [
{ mouse = "Right", action = "Paste" },
]

[window]
opacity = 0.9
blur = true
title = "Alacritty"
dynamic_title = false
padding = { x = 3, y = 3 }
dynamic_padding = true

[env]
term = "xterm-256color"

[font]
# normal = { family = "JetBrains Mono Nerd Font" }
normal = { family = "Monolisa" }

[colors.primary]
background = "#1a1a1c"
foreground = "#e5e5e7"
dim_foreground = "#6e6e73"
bright_foreground = "#e5e5e7"

[colors.cursor]
text = "#1a1a1c"
cursor = "#ffd7b5"

[colors.vi_mode_cursor]
text = "#1a1a1c"
cursor = "#5e5ce6"

[colors.search.matches]
foreground = "#1a1a1c"
background = "#a1a1a6"

[colors.search.focused_match]
foreground = "#1a1a1c"
background = "#32d74b"

[colors.footer_bar]
foreground = "#1a1a1c"
background = "#a1a1a6"

[colors.hints.start]
foreground = "#1a1a1c"
background = "#ffd60a"

[colors.hints.end]
foreground = "#1a1a1c"
background = "#a1a1a6"

[colors.selection]
text = "#1a1a1c"
background = "#ffd7b5"

[colors.normal]
black = "#28282b"
red = "#ff453a"
green = "#32d74b"
yellow = "#ffd60a"
blue = "#0a84ff"
magenta = "#ff7ab2"
cyan = "#40c8e0"
white = "#48484a"

[colors.bright]
black = "#3a3a3d"
red = "#ff453a"
green = "#32d74b"
yellow = "#ffd60a"
blue = "#0a84ff"
magenta = "#ff7ab2"
cyan = "#40c8e0"
white = "#a1a1a6"

[[colors.indexed_colors]]
index = 16
color = "#ff9f0a"

[[colors.indexed_colors]]
index = 17
color = "#ffd7b5"

[terminal.shell]
program = "/usr/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

