#[colors.bright]
#black = "#444b6a"
#blue = "#7da6ff"
#cyan = "#0db9d7"
#green = "#b9f27c"
#magenta = "#bb9af7"
#red = "#ff7a93"
#white = "#acb0d0"
#yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#3f00ff" # indigo
cyan = "#41fdfe" # cyan
green = "#66f742" # lime
magenta = "#ff00cd" # magenta
red = "#fc0905" # red
white = "#787c99" 
yellow = "#ffda29" # yellow

#[colors.primary]
#background = "#1a1b26"
#foreground = "#a9b1d6"

[font]
size = 12.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

#[schemes.tokyo-night.normal]
#black = "#32344a"
#blue = "#7aa2f7"
#cyan = "#449dab"
#green = "#9ece6a"
#magenta = "#ad8ee6"
#red = "#f7768e"
#white = "#787c99"
#yellow = "#e0af68"

#[schemes.tokyo-night.primary]
#background = "#1a1b26"
#foreground = "#a9b1d6"

[window]
dynamic_title = false
opacity = 0.7
title = "Terminal"
